[build]
  # Build command for Vite React app
  command = "npm install && npm run build"
  # Directory where build output is placed
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # Production API URL - Update this to your backend URL
  VITE_API_URL = "https://your-backend-url.com/api"

# SPA redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Fix MIME type for JavaScript modules
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

# Enable gzip compression
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    
# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"