[build]
  # Build command for Vite React app - CACHE BUST 20250820
  command = "npm install && npm run build -- --force"
  # Directory where build output is placed
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # FINAL NUCLEAR FIX - Force clear cache
  CACHE_BUST = "20250820-final-nuclear-fix"

# Context-specific environment variables
[context.production.environment]
  VITE_API_URL = "https://thrift-ease.onrender.com/api"

[context.deploy-preview.environment]
  VITE_API_URL = "https://thrift-ease.onrender.com/api"

[context.branch-deploy.environment]
  VITE_API_URL = "https://thriftease-api-dev.onrender.com/api"

# SPA redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ignore builds when only backend changes
[build.ignore]
  command = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- backend/"

# Fix MIME type for JavaScript modules
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

# Enable gzip compression
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    
# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"