services:
  # Frontend (React with Vite)
  - type: web
    name: thrift-ease
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: VITE_API_BASE_URL
        value: https://thrift-ease-backend.onrender.com

  # Backend API
  - type: web
    name: thrift-ease-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
