services:
  # Backend API
  - type: web
    name: thrift-ease-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
  
  # Frontend (Node.js with Express for SPA routing)
  - type: web
    name: thrift-ease-frontend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
