services:
  - type: web
    name: thriftease-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: thriftease-db
          property: connectionString
      - key: CORS_ORIGINS
        value: https://thriftease.netlify.app,http://localhost:3000,http://localhost:5173
databases:
  - name: thriftease-db
    databaseName: thriftease
    user: thriftease
