services:
  # Backend API (Render)
  - type: web
    name: thrift-ease-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: FLASK_ENV
        value: production
